# Generated by Django 6.1.1 on 2026-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_topics_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_state',
            field=models.CharField(default='TEACHING', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weak_topics_csv',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skill_level',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='target_topic',
            field=models.CharField(blank=True, default='Python Basics & Syntax', max_length=255, null=True),
        ),
    ]
